apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 210-azure-portworx-storage
  labels:
    type: software
    code: '210'
    platform: azure
  annotations:
    displayName: Azure - Portworx Cluster Storage
    description: Installs Portworx into an OCP cluster on Azure
spec:
  modules:
    - name: azure-portworx
      alias: azure-portworx
      version: v0.1.0
      variables:
        - name: azure_client_id
          alias: client_id
          scope: global
        - name: azure_client_secret
          alias: client_secret
          scope: global
        - name: azure_subscription_id
          alias: subscription_id
          scope: global
        - name: azure_tenant_id
          alias: tenant_id
          scope: global
        - name: azure-portworx_cluster_type
          value: IPI
    - name: ocp-login
      alias: cluster
      version: v1.3.1
  variables:
    - name: subscription_id
      type: string
      description: >-
        The subscription id of the Azure account where the OpenShift cluster has
        been provisioned
    - name: tenant_id
      type: string
      description: >-
        The tenant id of the Azure account where the OpenShift cluster has been
        provisioned
    - name: client_id
      type: string
      description: The client id used to access the Azure account
    - name: client_secret
      type: string
      description: The client secret used to access the Azure account
    - name: azure-portworx_portworx_spec_file
      type: string
      description: >-
        The path to the file that contains the yaml spec for the Portworx
        config. Either the `portworx_spec_file` or `portworx_spec` must be
        provided. The instructions for creating this configuration can be found
        at
        https://github.com/cloud-native-toolkit/terraform-azure-portworx/blob/main/PORTWORX_CONFIG.md
      defaultValue: ''
    - name: azure-portworx_portworx_spec
      type: string
      description: >-
        The yaml spec for the Portworx config. Either the `portworx_spec_file`
        or `portworx_spec` must be provided. The instructions for creating this
        configuration can be found at
        https://github.com/cloud-native-toolkit/terraform-azure-portworx/blob/main/PORTWORX_CONFIG.md
      defaultValue: ''
    - name: azure-portworx_enable_encryption
      type: bool
      description: Flag indicating portworx volumes should be encrypted
      defaultValue: false
    - name: server_url
      type: string
      description: The url for the OpenShift api
    - name: cluster_login_token
      type: string
      description: Token used for authentication
      sensitive: true
